title: Peculiar Genomic Observations
url: https://kamilsjaron.github.io/peculiar-genomic-observations/

theme: minima
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
        layout: "observation"
        permalink: "/:year/:month/:title.html"
